import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { Dirent } from 'node:fs';
import type { SkinIR, SkinNode } from './ast.js';
import type { Project } from '../project.js';

/**
 * Project-root-relative path of the generated skin-part declaration.
 */
export const SKIN_PARTS_DECLARATION_PATH = '.kurot/skin-parts.d.ts';

interface SkinPartType {
	readonly name: string;
	readonly className: string;
	readonly module: string;
}

interface SkinHostType {
	readonly className: string;
	readonly module: string;
	readonly skinName: string;
}

/**
 * Generates the project declaration that augments `@kurot/ui`'s
 * `SkinPartsMap` with every compiled skin and its complete named part set.
 */
export async function generateSkinPartsDeclaration(project: Project, skins: readonly SkinIR[]): Promise<string> {
	const declarationFile = path.join(project.root, SKIN_PARTS_DECLARATION_PATH);
	const entries = skins
		.map(skin => ({
			className: skin.className,
			parts: collectSkinParts(project, declarationFile, skin),
		}))
		.sort((a, b) => a.className.localeCompare(b.className));
	const modules = [...new Set(entries.flatMap(entry => entry.parts.map(part => part.module)))].sort();
	const aliases = new Map(modules.map((module, index) => [module, `SkinPartModule${index}`]));
	const hosts = await collectSkinHosts(project, declarationFile, entries.map(entry => entry.className));
	const lines = ['// Generated by @kurot/cli from compiled EXML skins.', '// @generated — do not edit manually.', ''];

	for (const module of modules) {
		lines.push(`import type * as ${aliases.get(module)} from ${JSON.stringify(module)};`);
	}
	if (modules.length > 0) {
		lines.push('');
	}

	lines.push('declare module "@kurot/ui" {', '\tinterface SkinPartsMap {');
	for (const entry of entries) {
		lines.push(`\t\t${JSON.stringify(entry.className)}: {`);
		for (const part of entry.parts) {
			lines.push(`\t\t\treadonly ${JSON.stringify(part.name)}: ${aliases.get(part.module)}.${part.className};`);
		}
		lines.push('\t\t};');
	}
	lines.push('\t}', '}', '');

	for (const host of hosts) {
		lines.push(
			`declare module ${JSON.stringify(host.module)} {`,
			`\tinterface ${host.className} {`,
			`\t\treadonly skinParts: import("@kurot/ui").SkinPartsOf<${JSON.stringify(host.skinName)}>;`,
			'\t}',
			'}',
			'',
		);
	}

	lines.push('export {};', '');
	return lines.join('\n');
}

/**
 * Finds project classes whose skin is selected explicitly, by reusable-component
 * configuration, or by an unambiguous `<ClassName>Skin` naming convention.
 */
async function collectSkinHosts(
	project: Project,
	declarationFile: string,
	skinNames: readonly string[],
): Promise<SkinHostType[]> {
	const files = await collectTypeScriptFiles(project.srcDir);
	const hosts = new Map<string, SkinHostType>();
	const skinNameSet = new Set(skinNames);

	for (const component of project.components) {
		if (!skinNameSet.has(component.skinClass)) {
			continue;
		}

		const relative = path.relative(path.dirname(declarationFile), component.source).replace(/\.tsx?$/, '.js');
		const module = toModuleSpecifier(relative);
		hosts.set(module, {
			className: component.name,
			module,
			skinName: component.skinClass,
		});
	}

	for (const file of files) {
		const className = path.basename(file).replace(/\.tsx?$/, '');
		if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(className)) {
			continue;
		}

		const source = stripComments(await fs.readFile(file, 'utf-8'));
		if (!hasNamedClassExport(source, className)) {
			continue;
		}

		const match = /\bthis\.skinName\s*=\s*(['"])([^'"]+)\1/.exec(source);
		const explicitSkinName = match?.[2];
		if (explicitSkinName && !skinNameSet.has(explicitSkinName)) {
			continue;
		}
		const conventionalSkinNames = skinNames.filter(
			skinName => getSkinShortName(skinName) === `${className}Skin`,
		);
		const skinName = explicitSkinName ?? (conventionalSkinNames.length === 1 ? conventionalSkinNames[0] : undefined);
		if (!skinName) {
			continue;
		}

		const relative = path.relative(path.dirname(declarationFile), file).replace(/\.tsx?$/, '.js');
		const module = toModuleSpecifier(relative);
		hosts.set(module, {
			className,
			module,
			skinName,
		});
	}

	return [...hosts.values()].sort((a, b) => a.module.localeCompare(b.module));
}

function getSkinShortName(skinName: string): string {
	return skinName.slice(skinName.lastIndexOf('.') + 1);
}

async function collectTypeScriptFiles(directory: string): Promise<string[]> {
	const files: string[] = [];

	async function walk(current: string): Promise<void> {
		let entries: Dirent[];
		try {
			entries = await fs.readdir(current, { withFileTypes: true });
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
				return;
			}
			throw error;
		}

		for (const entry of entries) {
			const absolute = path.join(current, entry.name);
			if (entry.isDirectory()) {
				await walk(absolute);
			} else if (entry.isFile() && /\.tsx?$/.test(entry.name) && !entry.name.endsWith('.d.ts')) {
				files.push(absolute);
			}
		}
	}

	await walk(directory);
	return files.sort();
}

function stripComments(source: string): string {
	return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

function hasNamedClassExport(source: string, className: string): boolean {
	const escaped = className.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	if (new RegExp(`\\bexport\\s+(?:default\\s+)?class\\s+${escaped}\\b`).test(source)) {
		return true;
	}

	const declared = new RegExp(`\\bclass\\s+${escaped}\\b`).test(source);
	const exported = new RegExp(`\\bexport\\s*\\{[^}]*\\b${escaped}\\b[^}]*\\}`, 's').test(source);
	return declared && exported;
}

function toModuleSpecifier(value: string): string {
	const normalized = value.split(path.sep).join('/');
	return normalized.startsWith('.') ? normalized : `./${normalized}`;
}

function collectSkinParts(project: Project, declarationFile: string, skin: SkinIR): SkinPartType[] {
	const nodes = new Map<string, SkinNode>();
	collectNodes(skin.children, nodes);
	collectNodes(skin.declarations, nodes);
	for (const property of skin.propertyChildren) {
		collectNodes(
			property.nodes.filter((node): node is SkinNode => typeof node !== 'string'),
			nodes,
		);
	}

	return skin.skinParts.map(name => {
		const node = nodes.get(name);
		if (!node) {
			throw new Error(`Skin part "${name}" in ${skin.className} has no matching EXML node.`);
		}
		return {
			name,
			className: node.className,
			module: resolveTypeModule(project, declarationFile, node),
		};
	});
}

function collectNodes(source: readonly SkinNode[], target: Map<string, SkinNode>): void {
	for (const node of source) {
		if (node.id) {
			target.set(node.id, node);
		}
		collectNodes(node.children, target);
		for (const property of node.propertyChildren) {
			collectNodes(
				property.nodes.filter((child): child is SkinNode => typeof child !== 'string'),
				target,
			);
		}
	}
}

function resolveTypeModule(project: Project, declarationFile: string, node: SkinNode): string {
	const namespace = project.customNamespaces.find(candidate => candidate.specifier === node.module);
	if (!namespace) {
		return node.module;
	}

	const component = namespace.components?.find(candidate => candidate.name === node.className);
	const source = component?.source ?? namespace.entry;
	if (!source) {
		return node.module;
	}

	const relative = path.relative(path.dirname(declarationFile), source).replace(/\.tsx?$/, '.js');
	const specifier = relative.split(path.sep).join('/');
	return specifier.startsWith('.') ? specifier : `./${specifier}`;
}
