import * as path from 'node:path';
import type { SkinIR, SkinNode } from './ast.js';
import type { Project } from '../project.js';

/**
 * Project-root-relative path of the generated skin-part declaration.
 */
export const SKIN_PARTS_DECLARATION_PATH = '.kurot/skin-parts.d.ts';

interface SkinPartType {
	readonly name: string;
	readonly className: string;
	readonly module: string;
}

/**
 * Generates the project declaration that augments `@kurot/ui`'s
 * `SkinPartsMap` with every compiled skin and its complete named part set.
 */
export function generateSkinPartsDeclaration(project: Project, skins: readonly SkinIR[]): string {
	const declarationFile = path.join(project.root, SKIN_PARTS_DECLARATION_PATH);
	const entries = skins
		.map(skin => ({
			className: skin.className,
			parts: collectSkinParts(project, declarationFile, skin),
		}))
		.sort((a, b) => a.className.localeCompare(b.className));
	const modules = [...new Set(entries.flatMap(entry => entry.parts.map(part => part.module)))].sort();
	const aliases = new Map(modules.map((module, index) => [module, `SkinPartModule${index}`]));
	const lines = ['// Generated by @kurot/cli from compiled EXML skins.', '// @generated — do not edit manually.', ''];

	for (const module of modules) {
		lines.push(`import type * as ${aliases.get(module)} from ${JSON.stringify(module)};`);
	}
	if (modules.length > 0) {
		lines.push('');
	}

	lines.push('declare module "@kurot/ui" {', '\tinterface SkinPartsMap {');
	for (const entry of entries) {
		lines.push(`\t\t${JSON.stringify(entry.className)}: {`);
		for (const part of entry.parts) {
			lines.push(`\t\t\treadonly ${JSON.stringify(part.name)}: ${aliases.get(part.module)}.${part.className};`);
		}
		lines.push('\t\t};');
	}
	lines.push('\t}', '}', '', 'export {};', '');
	return lines.join('\n');
}

function collectSkinParts(project: Project, declarationFile: string, skin: SkinIR): SkinPartType[] {
	const nodes = new Map<string, SkinNode>();
	collectNodes(skin.children, nodes);
	collectNodes(skin.declarations, nodes);
	for (const property of skin.propertyChildren) {
		collectNodes(
			property.nodes.filter((node): node is SkinNode => typeof node !== 'string'),
			nodes,
		);
	}

	return skin.skinParts.map(name => {
		const node = nodes.get(name);
		if (!node) {
			throw new Error(`Skin part "${name}" in ${skin.className} has no matching EXML node.`);
		}
		return {
			name,
			className: node.className,
			module: resolveTypeModule(project, declarationFile, node),
		};
	});
}

function collectNodes(source: readonly SkinNode[], target: Map<string, SkinNode>): void {
	for (const node of source) {
		if (node.id) {
			target.set(node.id, node);
		}
		collectNodes(node.children, target);
		for (const property of node.propertyChildren) {
			collectNodes(
				property.nodes.filter((child): child is SkinNode => typeof child !== 'string'),
				target,
			);
		}
	}
}

function resolveTypeModule(project: Project, declarationFile: string, node: SkinNode): string {
	const namespace = project.customNamespaces.find(candidate => candidate.specifier === node.module);
	if (!namespace) {
		return node.module;
	}

	const component = namespace.components?.find(candidate => candidate.name === node.className);
	const source = component?.source ?? namespace.entry;
	if (!source) {
		return node.module;
	}

	const relative = path.relative(path.dirname(declarationFile), source).replace(/\.tsx?$/, '.js');
	const specifier = relative.split(path.sep).join('/');
	return specifier.startsWith('.') ? specifier : `./${specifier}`;
}
