import { EventDispatcher, DisplayObject, Event, type EventMap } from '@blakron/core';
import { PropertyEvent } from '../events/PropertyEvent.js';
import type { State } from '../states/State.js';
import type { Component } from './Component.js';
import type { Watcher } from '../binding/Watcher.js';

/**
 * EventMap for Skin. Skins dispatch PropertyEvent when hostComponent changes.
 */
export interface SkinEvents extends EventMap {
	[PropertyEvent.PROPERTY_CHANGE]: PropertyEvent;
}

/**
 * Base class for all UI skins.
 *
 * Skins are typically generated by the EXML compiler (`@blakron/cli`).
 * A skin holds the visual $children of a Component and exposes named
 * "skin parts" (e.g. `labelDisplay`, `iconDisplay`) that the host
 * component binds to via `partAdded()` / `partRemoved()`.
 *
 * The skin also owns the view-state list (`states`) and applies state
 * changes to its $children when `currentState` changes.
 */
export class Skin extends EventDispatcher<SkinEvents> {
	// ── Instance fields ───────────────────────────────────────────────────

	public skinParts: string[] = [];
	public width: number = NaN;
	public height: number = NaN;
	public minWidth: number = 0;
	public maxWidth: number = 100000;
	public minHeight: number = 0;
	public maxHeight: number = 100000;
	public states: State[] = [];

	/**
	 * Watchers created by EXML bindings (e.g. `{data}`). The runtime appends
	 * every {@link Watcher} instance created by the skin factory so they can
	 * be unwound together via {@link unwatchAll} when the skin is replaced.
	 */
	public $watchers: Watcher[] = [];

	private _elementsContent: DisplayObject[] = [];
	private _hostComponent?: Component;
	private _currentState = '';
	private _stateInitialized = false;

	// ── Getters / Setters ─────────────────────────────────────────────────

	public get elementsContent(): DisplayObject[] {
		return this._elementsContent;
	}

	public set elementsContent(value: DisplayObject[]) {
		this._elementsContent = value ?? [];
	}

	public get hostComponent(): Component | undefined {
		return this._hostComponent;
	}

	public set hostComponent(value: Component | undefined) {
		if (this._hostComponent === value) return;

		const oldHost = this._hostComponent;
		if (oldHost) {
			oldHost.removeEventListener(Event.ADDED_TO_STAGE, this._onHostAddedToStage);
			if (this._stateInitialized) {
				this._removeState(this._currentState, oldHost);
				this._stateInitialized = false;
			}
		}

		this._hostComponent = value;

		if (value) {
			if (value.stage) {
				this._initializeStates();
			} else {
				value.once(Event.ADDED_TO_STAGE, this._onHostAddedToStage);
			}
		}

		PropertyEvent.dispatchPropertyEvent(this, 'hostComponent');
	}

	public get currentState(): string {
		return this._currentState;
	}

	public set currentState(value: string) {
		if (this._currentState === value) return;
		const old = this._currentState;
		this._currentState = value;
		if (this._stateInitialized && this._hostComponent) {
			this._applyState(old, value);
		}
	}

	// ── Public methods ────────────────────────────────────────────────────

	/**
	 * Get a skin part by name. Used by Component to bind parts.
	 */
	public getPart(name: string): unknown {
		return (this as Record<string, unknown>)[name];
	}

	/**
	 * Unwatch every binding created from this skin.
	 * Called by the host component when the skin is detached or replaced
	 * so stale watchers don't leak or fire on the wrong host.
	 */
	public unwatchAll(): void {
		if (this.$watchers && this.$watchers.length > 0) {
			for (const watcher of this.$watchers) {
				watcher.unwatch();
			}
			this.$watchers.length = 0;
		}
	}

	public hasState(stateName: string): boolean {
		return this.states.some(s => s.name === stateName);
	}

	// ── Private methods ───────────────────────────────────────────────────

	private _onHostAddedToStage = (): void => {
		this._initializeStates();
	};

	private _initializeStates(): void {
		if (this._stateInitialized) return;
		this._stateInitialized = true;
		this._applyState('', this._currentState);
	}

	private _applyState(fromState: string, toState: string): void {
		if (!this.states || this.states.length === 0) return;

		const oldState = this.states.find(s => s.name === fromState);
		if (oldState) {
			for (const override of oldState.overrides) {
				override.remove(this._hostComponent!, this);
			}
		}

		const newState = this.states.find(s => s.name === toState);
		if (newState) {
			for (const override of newState.overrides) {
				override.apply(this._hostComponent!, this);
			}
		}
	}

	private _removeState(stateName: string, host: Component): void {
		const state = this.states.find(s => s.name === stateName);
		if (!state) return;
		for (const override of state.overrides) {
			override.remove(host, this);
		}
	}
}
